application: vmlmcdn
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
  mime_type: text/css
- url: /js
  static_dir: js
  mime_type: text/javascript
- url: /html
  static_dir: html
  mime_type: text/html